### ISSUE TITLE
temp.nctime

### ISSUE THREAD

**Issue by raishalovindeer** [jporobicg/SSAM_physics#1]
Matlab does not recognize `temp.nctime` in line 68 of `Get_physics_main_SS.m`.  Is that a variable, function, or nested structure that I should have supplied?

**Comment by jporobicg** [comment]
That object `temp.nctime` was created from an old piece of code. that I was using to correct the time variable. When I download it the first time the files I did a mistake with the **R** code and I was repeating the days, So, I created that code to deal with that issue. So technically you won't need that. I just removed the remains of that code. It should work now.

**Comment by raishalovindeer** [comment]
ok great. Thanks.
